# Generated by Django 5.0.14 on 2026-09-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('category', models.CharField(max_length=32, verbose_name='设备类别')),
                ('area', models.CharField(max_length=32, verbose_name='车间/区域')),
                ('manufacturer', models.CharField(blank=True, max_length=64, verbose_name='制造商')),
                ('status', models.CharField(choices=[('running', '运行中'), ('idle', '待机'), ('down', '停机'), ('maintenance', '维修中')], default='running', max_length=16, verbose_name='设备状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='适用设备类别')),
                ('name', models.CharField(max_length=64, verbose_name='点检项')),
                ('kind', models.CharField(choices=[('param', '参数'), ('check', '检查项')], default='param', max_length=8, verbose_name='类型')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='单位')),
                ('lower_limit', models.FloatField(blank=True, null=True, verbose_name='下限')),
                ('upper_limit', models.FloatField(blank=True, null=True, verbose_name='上限')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '点检项',
                'verbose_name_plural': '点检项',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='班次名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '班次',
                'verbose_name_plural': '班次',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DowntimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fault', '故障停机'), ('planned', '计划停机'), ('other', '其他')], default='fault', max_length=16, verbose_name='停机原因')),
                ('remark', models.TextField(blank=True, verbose_name='停机说明')),
                ('stopped_at', models.DateTimeField(auto_now_add=True, verbose_name='停机时间')),
                ('resumed_at', models.DateTimeField(blank=True, null=True, verbose_name='复机时间')),
                ('resume_confirm_by', models.CharField(blank=True, max_length=32, verbose_name='复机确认人')),
                ('resume_note', models.TextField(blank=True, verbose_name='复机说明')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='inspection.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '停机记录',
                'verbose_name_plural': '停机记录',
                'ordering': ['-stopped_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='任务单号')),
                ('task_date', models.DateField(verbose_name='点检日期')),
                ('status', models.CharField(choices=[('pending', '待点检'), ('in_progress', '点检中'), ('done', '已完成'), ('abnormal', '有异常'), ('missed', '漏检')], default='pending', max_length=16, verbose_name='状态')),
                ('inspector', models.CharField(blank=True, max_length=32, verbose_name='点检人')),
                ('remark', models.TextField(blank=True, verbose_name='任务备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='inspection.equipment', verbose_name='设备')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='inspection.shift', verbose_name='班次')),
            ],
            options={
                'verbose_name': '点检任务',
                'verbose_name_plural': '点检任务',
                'ordering': ['-task_date', 'shift__start_time', 'equipment__code'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='实测值')),
                ('normal', models.BooleanField(default=True, verbose_name='是否正常')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='inspection.inspectionitem', verbose_name='点检项')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='inspection.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '点检记录',
                'verbose_name_plural': '点检记录',
            },
        ),
        migrations.CreateModel(
            name='AbnormalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='异常单号')),
                ('reading_value', models.CharField(blank=True, max_length=64, verbose_name='异常读数')),
                ('phenomenon', models.TextField(verbose_name='异常现象')),
                ('severity', models.CharField(choices=[('low', '一般'), ('high', '严重'), ('critical', '紧急')], default='low', max_length=8, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '待派单'), ('dispatched', '已派单'), ('resolved', '已处理'), ('closed', '已关闭')], default='open', max_length=16, verbose_name='状态')),
                ('reporter', models.CharField(blank=True, max_length=32, verbose_name='上报人')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abnormals', to='inspection.equipment', verbose_name='设备')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection.inspectionitem', verbose_name='点检项')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abnormals', to='inspection.task', verbose_name='点检任务')),
            ],
            options={
                'verbose_name': '异常报告',
                'verbose_name_plural': '异常报告',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='工单号')),
                ('assignee', models.CharField(max_length=32, verbose_name='维修负责人')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('status', models.CharField(choices=[('assigned', '已派单'), ('repairing', '维修中'), ('done', '已完成'), ('accepted', '已验收')], default='assigned', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='派单时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开工时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完工时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='验收时间')),
                ('result', models.TextField(blank=True, verbose_name='维修结果')),
                ('abnormal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order', to='inspection.abnormalreport', verbose_name='异常报告')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='inspection.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '维修工单',
                'verbose_name_plural': '维修工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('equipment', 'shift', 'task_date'), name='uniq_equipment_shift_date'),
        ),
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('item', 'task')},
        ),
    ]
