# Generated by Django 5.0.14 on 2026-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_no',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='任务单号'),
        ),
    ]
