# Generated by Django 5.0.14 on 2026-09-12 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_alter_task_task_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='uniq_equipment_shift_date',
        ),
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('normal', '常规'), ('recheck', '补检')], default='normal', max_length=8, verbose_name='任务类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechecks', to='inspection.task', verbose_name='补检来源任务'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('equipment', 'shift', 'task_date', 'kind'), name='uniq_equipment_shift_date_kind'),
        ),
    ]
