# Generated by Django 5.0.14 on 2026-09-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_remove_task_uniq_equipment_shift_date_task_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnormalreport',
            name='void_reason',
            field=models.TextField(blank=True, verbose_name='作废原因'),
        ),
        migrations.AddField(
            model_name='abnormalreport',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='作废时间'),
        ),
        migrations.AddField(
            model_name='abnormalreport',
            name='voided_by',
            field=models.CharField(blank=True, max_length=32, verbose_name='作废人'),
        ),
        migrations.AlterField(
            model_name='abnormalreport',
            name='status',
            field=models.CharField(choices=[('open', '待派单'), ('dispatched', '已派单'), ('resolved', '已处理'), ('closed', '已关闭'), ('voided', '已作废')], default='open', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('assigned', '已派单'), ('repairing', '维修中'), ('done', '已完成'), ('accepted', '已验收'), ('cancelled', '已作废')], default='assigned', max_length=16, verbose_name='状态'),
        ),
    ]
